import React from 'react';

function getLevelLabel(level) {
  return level || '';
}

export default function PrintView({ scheduleData, dayLabel }) {
  if (!scheduleData) return null;

  const { time_slots, lessons } = scheduleData;

  const lessonsByTime = {};
  lessons.forEach(l => {
    lessonsByTime[l.start_time] = lessonsByTime[l.start_time] || [];
    lessonsByTime[l.start_time].push(l);
  });

  return (
    <div className="print-view">
      <div className="print-header">
        <div className="print-title">Excel Aquatics — Daily Schedule</div>
        <div className="print-subtitle">{dayLabel || ''}</div>
      </div>

      <table className="print-table">
        <thead>
          <tr>
            <th>Time</th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {time_slots.map(time => {
            const lanes = lessonsByTime[time] || [];
            return (
              <tr key={time}>
                <td className="print-time-cell">{time}</td>
                {[0, 1, 2, 3].map(laneIdx => {
                  const lesson = lanes[laneIdx];
                  return (
                    <td key={laneIdx} className="print-lane-cell">
                      {lesson ? (
                        <div>
                          <div className="print-instructor">
                            {lesson.assigned_instructor || 'Unassigned'}
                          </div>
                          {(lesson.students || []).map((s, i) => (
                            <div key={i} className="print-student">
                              <span className="print-student-name">{s.first} {s.last}</span>
                              {s.swim_level && <span className="print-level"> ({getLevelLabel(s.swim_level)})</span>}
                              {s.is_adaptive && <span className="print-adaptive-tag"> [Adaptive]</span>}
                              {s.roll_notes && <div className="print-notes">{s.roll_notes}</div>}
                            </div>
                          ))}
                        </div>
                      ) : (
                        <span className="print-empty">—</span>
                      )}
                    </td>
                  );
                })}
              </tr>
            );
          })}
        </tbody>
      </table>

      <div className="print-footer">
        Generated by Excel Aquatics Scheduling Tool
      </div>
    </div>
  );
}
